name: Move issur to To do

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: WebThings Cloud
          column: To do
          repo-token: ${{ secrets.GITHUB_TOKEN }}
